import { analyzeResumeAgent } from "../agentic-mock-test/resumeAnalyzer.js";
import prisma from "../prismaClient.js";

import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pdfParse = require("pdf-parse-fork");

async function extractTextFromBuffer(buffer, mimetype) {
  if (mimetype === "application/pdf") {
    const data = await pdfParse(buffer);
    return data.text;
  }
  return buffer.toString("utf-8").replace(/[^\x20-\x7E\t\n\r]/g, "");
}

export const uploadAndAnalyzeResume = async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: "Missing file" });
    const { company, role, experience, jobDescription } = req.body;
    
    const rawResumeText = await extractTextFromBuffer(req.file.buffer, req.file.mimetype);
    const reportAnalysis = await analyzeResumeAgent({ resumeText: rawResumeText, jobDescription, targetRole: role, experienceLevel: experience });

    const savedRecord = await prisma.resumeAnalysis.create({
      data: {
        // Real owner when signed in. Anonymous runs are still allowed (the
        // analyser is public), but they are tagged per-request so they can
        // never be listed as somebody else's history.
        userId: req.userId || `anon:${req.ip || "unknown"}`,
        fileName: req.file.originalname,
        targetCompany: company || "Generic",
        targetRole: role,
        experienceLevel: experience,
        jobDescription: jobDescription || "",
        overallScore: Number(reportAnalysis.overallScore) || 0,
        matchPercentage: Number(reportAnalysis.matchPercentage) || 0,
        radarMetrics: reportAnalysis.radarMetrics || {},
        strengths: reportAnalysis.strengths || [],
        weaknesses: reportAnalysis.weaknesses || [],
        missingSkills: reportAnalysis.missingSkills || [],
        
        // Structured JSON container to bypass unknown argument errors
        lintChecks: {
          ...reportAnalysis.lintChecks,
          sections: reportAnalysis.sections,
          skillAnalysis: reportAnalysis.skillAnalysis,
          roleAlignment: reportAnalysis.roleAlignment,
          projectEvaluation: reportAnalysis.projectEvaluation,
          experienceEvaluation: reportAnalysis.experienceEvaluation,
          keywordAnalysis: reportAnalysis.keywordAnalysis,
          formatting: reportAnalysis.formatting,
          readability: reportAnalysis.readability,
          companySimulation: reportAnalysis.companySimulation,
          improvements: reportAnalysis.improvements,
          rewrittenBullets: reportAnalysis.rewrittenBullets,
          interviewProbability: reportAnalysis.interviewProbability,
          finalVerdict: reportAnalysis.finalVerdict
        },

        // Flattened suggestions to match Prisma model
        suggestions: {
          bulletRewrites: reportAnalysis.suggestions?.bulletRewrites || reportAnalysis.rewrittenBullets?.map(b => b.improved) || [],
          projectImprovements: reportAnalysis.suggestions?.projectImprovements || reportAnalysis.improvements?.projectRecommendations || [],
          metricAdditions: reportAnalysis.suggestions?.metricAdditions || reportAnalysis.improvements?.highImpactChanges || [],
          resumeOptimization: reportAnalysis.suggestions?.resumeOptimization || reportAnalysis.improvements?.resumeOptimization || "Optimize metrics."
        }
      }
    });

    return res.status(200).json({ success: true, data: savedRecord });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: err.message });
  }
};

/**
 * A signed-in user's own past analyses.
 *
 * Previously this returned EVERY row in the table to anyone who asked — other
 * people's resumes, target companies and weaknesses included. It is now scoped
 * to req.userId, and returns an empty list rather than a leak when the caller
 * is not signed in.
 *
 * Summary fields only: the list view does not need the full report payload,
 * and those payloads are large.
 */
export const getAnalysisHistory = async (req, res) => {
  if (!req.userId) {
    return res.status(200).json({ success: true, data: [], anonymous: true });
  }
  const history = await prisma.resumeAnalysis.findMany({
    where: { userId: req.userId },
    orderBy: { createdAt: "desc" },
    take: 50,
    select: {
      id: true,
      fileName: true,
      targetRole: true,
      targetCompany: true,
      experienceLevel: true,
      overallScore: true,
      matchPercentage: true,
      createdAt: true,
    },
  });
  return res.status(200).json({ success: true, data: history });
};

/**
 * Full stored report, so a past analysis can be reopened exactly as it was.
 *
 * Everything needed to re-render is already persisted as JSON, so nothing is
 * regenerated by the model and no PDF is stored anywhere.
 */
export const getAnalysisById = async (req, res) => {
  try {
    const record = await prisma.resumeAnalysis.findUnique({ where: { id: req.params.id } });
    if (!record) return res.status(404).json({ error: "Analysis not found" });
    // Ownership check, so an id cannot be guessed into someone else's report.
    if (!req.userId || record.userId !== req.userId) {
      return res.status(403).json({ error: "Not your analysis" });
    }
    return res.status(200).json({ success: true, data: record });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};